src/Entity/Messages.php
<?php

namespace App\Entity;

use DateTimeInterface;
use App\Entity\Utilisateurs;
    use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\MessagesRepository;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=MessagesRepository::class)
 * @UniqueEntity("titre_message")
 */

class Messages
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $titre_message;

    /**
     * @ORM\Column(type="string", length=255, unique=true, nullable=true)
     * @Gedmo\Slug(fields={"titre_message"})
     */
    private $slug;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $creer_date;

        /**
     * @ORM\Column(type="boolean")
     */
    private $si_messageLu = 0;

    /**
     * @ORM\ManyToOne(targetEntity=Utilisateurs::class, inversedBy="message_envoyer", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $expediteur;

    /**
     * @ORM\ManyToOne(targetEntity=Utilisateurs::class, inversedBy="message_recu", cascade={"persist"})
     */
    private $medias;

    /**
     * @ORM\ManyToOne(targetEntity=Utilisateurs::class, inversedBy="message_recu", cascade={"persist"})
     */
    private $destinataire = [];
    
    public function __construct()
    {
        $this->creer_date = new 
        \DateTime();
        }

    public function getId       (): ?int
    {
        return $this->id;
    }

    public function getTitreMessage(): ?string
    {
        return $this->titre_message;
    }

    public function setTitreMessage(?string $titre_message): self
    {
        $this->titre_message = $titre_message;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSiMessageLu(): ?bool
    {
        return $this->si_messageLu;
    }

    public function setSiMessageLu(bool $si_messageLu): self
    {
        $this->si_messageLu = $si_messageLu;

        return $this;
    }

    public function getCreerDate(): ?\DateTimeInterface
    {
        return $this->creer_date;
    }

    public function setCreerDate(\DateTimeInterface $creer_date): self
    {
        $this->creer_date = $creer_date;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getExpediteur(): ?Utilisateurs
    {
        return $this->expediteur;
    }

    public function setExpediteur(?Utilisateurs $expediteur): self
    {
        $this->expediteur = $expediteur;

        return $this;
    }


    public function getMedias(): ?Utilisateurs
    {
        return $this->medias;
    }

    public function setMedias(?Utilisateurs $medias): self
    {
        $this->medias = $medias;

        return $this;
    }

    public function getDestinataire(): ?Utilisateurs
    {
        return $this->destinataire;
    }

    public function setDestinataire(?Utilisateurs $destinataire): self
    {
        $this->destinataire = $destinataire;

        return $this;
    }

    

}

src/Form/MessagesType.php
<?php

namespace App\Form;

use App\Entity\Contacts;
use App\Entity\Messages;
use App\Entity\Medias;

use App\Entity\Utilisateurs;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;

use Symfony\Component\Form\AbstractType;

use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

use Symfony\Component\Validator\Constraints\IsTrue;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
//use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\BirthdayType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;

use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
//use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class MessagesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            
        ->add('titre_message', TextType::class, [
            'label' => 'Le titre de votre message !',
            'attr' => ['placeholder' => 'Titre'],
                'constraints' => [
                    new Length([
                    'min' => 2 ,
                    'max' => 20
                ]),
                    new NotBlank([
                        'message' => 'Entrez votre titre',
                    ]),
                ],
                'required' => true
        ])
            
        ->add('description' ,
                    TextareaType::class,[
                'label' =>'Description de votre message !' ,
                'attr' => ['placeholder' => 'Description'],
                'constraints' => [
                    new Length([
                    'min' => 2 ,
                    'max' => 700
                ]),
                    new NotBlank([
                        'message' => 'Entrez votre description',
                    ]),
                ],
'required' => true
        ])
        
        ->add('creer_date', BirthdayType::class, [
            'label' => 'Date cr"ation du message :',
            'required' => false,
            'widget' => 'single_text'
        ])

        ->add('si_messageLu', TextType::class, [
            'label' => 'Si le message est lu :',
            'required' => false
        ])
        
        ->add('expediteur', EntityType::class, [
            'label' =>'Expéditeur du message :',
                 //'placeholder' => 'Sélectionner',
                 // looks for choices from this entity
                 'class' =>Messages::class,
                 // Sur quelle propriete je fais le choix
                 'choice_label' => 'titre_message',
                 
                 // used to render a select box, check boxes or radios
             // 'multiple' => false,
                //'expanded' => true,)
//            'required' => false
        ])
        
        ->add('destinataire', EntityType::class, [
            'label' =>'Destinataire du message :',
                 //'placeholder' => 'Sélectionner',
                 // looks for choices from this entity
                 'class' =>Messages::class,
                 // Sur quelle propriete je fais le choix
                 'choice_label' => 'titre_message',
                 
                 // used to render a select box, check boxes or radios
             // 'multiple' => true,
                //'expanded' => true,)
//            'required' => true
        ])
        

        ;
        }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Messages::class,
        ]);
    }
}

src/Controller/MessagesController.php
<?php

namespace App\Controller;

use App\Entity\Messages;
use App\Form\MessagesType;
use App\Repository\MessagesRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;

//use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/messages")
 */
class MessagesController extends AbstractController
{
    /**
     * @Route("/", name="message_index")
     */
    public function index(MessagesRepository $messagesRepository, PaginatorInterface $pagi, Request $request): Response
    {
        $messages = $pagi->paginate(
            $messagesRepository->findWithPagination(),
            $request->query->getInt('page',1),10
                    
        );
        return $this->render('messages/index.html.twig', [
            'message' => $messagesRepository->findAll(),
        ]);
    }
    
/**
     * @Route("/formulaireMessages", name = "formulaireMessages_index", methods={"GET","POST"})
     */
    public function formulaireMessages(Request $request): Response
    {
        $messages = new Messages();
        
        $form = $this->createForm(MessagesType::class, $messages);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($messages);
            $entityManager->flush();
            $this->addFlash("success","La création a été effectuée avec succé !");

            return $this->redirectToRoute('message_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('messages/formulaireMessages.html.twig', [
            'message' => $messages,
            'formMessages' => $form->createView(),
        ]);
    }

    /**
     * @Route("/nouveauMessages", name="nouveauMessage_index", methods={"GET","POST"})
     */
    public function nouveauMessages(Request $request): Response
    {
        $messages = new Messages();
        $form = $this->createForm(MessagesType::class, $messages);
        
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($messages);
            $entityManager->flush();
            $this->addFlash("success","Enregistrement nouveau message a été effectuée avec succés !");

            return $this->redirectToRoute('message_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('messages/nouveauMessage.html.twig', [
            'message' => $messages,
            'formMessages' => $form->createView(),
        ]);
    }

    /**
     * @Route("/afficherMessage/{id}", name="afficherMessage_index", methods={"GET"})
     */
    public function afficherMessage(Messages $messages): Response
    {
        $this->addFlash("success","Affichage a été effectuée avec succés !");

        return $this->render('messages/afficherMessage.html.twig', [
            'message' => $messages,
        ]);
    }

/**
     * @Route("/modifierMessages/{id}", name="modifierMessage_index", methods={"GET","POST"})
     */
    public function modifierMessages(Request $request, Messages $messages): Response
    {
        $form = $this->createForm(MessagesType::class, $messages);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($messages);
            $entityManager->flush();
            $this->addFlash("success","La modification a été effectuée avec succés !");

            return $this->redirectToRoute('message_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('messages/modifierMessage.html.twig', [
            'message' => $messages,
            'formMessages' => $form->createView(),
        ]);
    }

// SUPPRESSION D'UN MESSAGE :
    /**
     * @Route("/supprimerMessages/{id}" , name="supprimerMessage_index", methods= {"GET","POST"})
     */
    public function supprimerMessages(Request $request, Messages $messages , EntityManagerInterface $entityManager) : Response 
    {           
            $entityManager->remove($messages);
            $entityManager->flush();
            $this->addFlash("success","La suppression a été effectuée avec succés !");

            return $this->redirectToRoute('message_index'); 
    }


/**
     * @Route("/messageEnvoyer", name="messageEnvoyer_index")
     */
    public function messageEnvoyer(Request $request, Messages $messages): Response
    {
        $messages = new Messages();
        $form = $this->createForm(MessagesType::class, $messages);
        
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $messages->setExpediteur($this->getUser());

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($messages);
            $entityManager->flush();

                    $this->addFlash("message", "Message envoyé avec succès.");
            return $this->redirectToRoute("message_index");
        }

        return $this->render("messages/messageEnvoyer.html.twig", [
            'message' => $messages,
                        "formMessages" => $form->createView()
        ]);
    }

    /**
     * @Route("/messagesRecu", name="messagesRecu_index")
     */
    public function messageReçu(Request $request, Messages $messages): Response
    {
        $this->addFlash("success","Message reçu a été effectuée avec succés !");

        return $this->render('messages/messagesReçu.html.twig'[
]);
    }

    /**
     * @Route("/listeMessagesEnvoyer", name="listeMessagesEnvoyer_index")
     */
    public function listeMessagesEnvoyer(Request $request, Messages $messages): Response
    {
        return $this->render('messages/listeMessagesEnvoyer.html.twig');
    }

    /**
     * @Route("/listeMessagesRecu", name="listeMessagesRecu_index")
     */
    public function listeMessagesRecu(Request $request, Messages $messages): Response
    {
        return $this->render('messages/listeMessagesRecu.html.twig');
    }


    /**
     * @Route("/messagesLu/{id}", name="messagesLu_index")
     */
    public function messageLu(Request $request, Messages $messages): Response
    {
        $messages->setSiMessageLu(true);

        $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($messages);
            $entityManager->flush();
            $this->addFlash("success","Le message a été lu avec succés !");

        return $this->render('messages/messagesLu.html.twig', compact("message")[
]);
    }



}

templates/message/afficherMessage.html.twig
{% extends 'base.html.twig' %}

{% block title %}

afficher message :
{% endblock %}

{% block content %}
    <h1>
    Afficher message :
    </h1>

<table border="1">
            <thead>
                <tr>
                    <th> Id </th>
                    <th> Titre du message </th>
                    <th> Description </th>
                    <th> Creer date </th>
                    <th> Si le message est lu </th>
                    <th> Expediteur </th>
                    <th> Destinataire </th>
</tr>
            </thead>
<tbody>
<tr>
                                <td> {{ message.id }} </td>
<td> {{ message.titreMessage }} </td>
                <td> {{ message.description }} </td>
                <td> {{ message.creerDate|date("d/m/Y") }} </td>
<td> {{ message.siMessageLu }} </td>
                <td> {{ message.expediteur.nom }} </td>
                <td> {{ message.destinataire.nom }} </td>
                </tr>
<tr>
<td><a href="{{ path('message_index') }}"> Retour à la liste des messages :</a></td><br>

</tr>
</tbody>
    </table>
    
    {% endblock %}

templates/message/base.html.twig
<!DOCTYPE html>
<html>

<head>
    <title>{% block title %}Symfony{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% block stylesheets %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/css/app.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('css/nabi.css') }}">
                        {% endblock %}
</head>

<body>
    <nav>
        <div class="nav-wrapper">
            <div class="container">
                
                <!-- <a href="{{ path('accueil_index') }}"> Accueil </a> -->
                <ul id="nav-mobile" class="right hide-on-med-and-down">
                    
                    {% if app.user %}
                    <li><a href="{{ path('accueil_index') }}"> accueil </a></li>

<li><a href="{{ path('pageAccueilGuinot_index') }}"> Page d'accueil de GUINOT ! </a></li>

<li><a href="{{ path('medias_index') }}"> Liste des médias ! </a></li>
<li><a href="{{ path('contacts_index') }}"> Liste des contacts ! </a></li>

<li><a href="{{ path('message_index') }}"> Liste des messages : </a></li>
<li><a href="{{ path('utilisateur_index') }}"> Liste des utilisateurs : </a></li>

                    <li><a href="{{ path('app_logout') }}"> se déconnecter </a></li>


{% if is_granted('ROLE_ADMIN') %}
<li><a href="{{ path('utilisateur_index') }}"> Liste des utilisateurs : </a></li>
<li><a href="{{ path('message_index') }}"> Liste des messages : </a></li>
{% endif %}


{% if is_granted('ROLE_ABONNER') %}
<li><a href="{{ path('pageAccueilEspacePerso_index') }}">Page d'accueil de votre espace perso ! </a> </li>
<li><a href="{{ path('monEspacePersonel_index') }}">Mon espace personnel : </a> </li>
{% endif %}


                    {% else %}
<li><a href="{{ path('accueil_index') }}"> accueil </a></li>
                    
                    <li><a href="{{ path('app_login') }}"> Se connecter </a> </li>
                    <li><a href="{{ path('app_register') }}"> Création de compte </a> </li>
                                <li><a href="{{ path('app_logout') }}"> se déconnecter </a></li>

<li><a href="{{ path('pageAccueilGuinot_index') }}"> Page d'accueil de GUINOT ! </a></li>

<li><a href="{{ path('medias_index') }}"> Liste des médias ! </a></li>
<li><a href="{{ path('contacts_index') }}"> Liste des contacts ! </a></li>

<li><a href="{{ path('message_index') }}"> accéder au service de tchat public !</a></li>
<li><a href="{{ path('utilisateur_index') }}"> Liste des utilisateurs : </a></li>
                                            
                                            {% endif %}

                    {% if 'register' == app.request.attributes.get('_route') %}
<li><a href="{{ path('utilisateur_index') }}"> Liste des utilisateurs : </a></li>

<li><a href="{{ path('message_index') }}"> Liste des messages </a> </li>
                    
                    {% endif %}
                        
                        {% if 'login' == app.request.attributes.get('_route') %}
<li><a href="{{ path('utilisateur_index') }}"> Liste des utilisateurs : </a></li>
<li><a href="{{ path('message_index') }}"> Liste des messages </a> </li>

                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    {% block content %}

    {% endblock %}

    {% block scripts %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

    <script type="text/javascript">
        $('select').formSelect();
    </script>
    {% endblock %}
</body>

</html>

templates/message/formulaireMessage.html.twig
    
{{ form_start(formMessages) }}

Titre du message: {{ form_widget(formMessages.titre_message) }}<br>
Description: {{ form_widget(formMessages.description) }} <br>
Créer date: {{ form_widget(formMessages.creer_date) }} <br>
Si le message est lu: {{ form_widget(formMessages.si_messageLu) }} <br>
Expediteur: {{ form_widget(formMessages.expediteur) }} <br>
Destinataire: {{ form_widget(formMessages.destinataire) }} <br>



<button type="submit" class="btn btn-success">envoyer</button>


      
    {{ form_end(formMessages) }}

templates/message/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} Liste des messages! {% endblock %}


{% block body %}

{% block content %}
<div>
    <h1>
     bienvenu(e) !
     Messagerie de Guinot :
     </h1>

    <br /><br />
    <hr />
<lu>
{#<li><a href="{{ path('expediteur_index') }}"> Le nom de l'expéditeur :</a></li>#}
{#<li><a href="{{ path('destinataire_index', {'id': message.id }) }}"> Le nom du déstinataire :</a></li>#}
{#<li><a href="{{ path('destinataire_index', {'id': message.id }) }}"> Le nom du déstinataire :</a></li>#}
{#<li><a href="{{ path('messageEnvoyer_index', {'id': message.id }) }}">Message envoyer</a></li>#}
{#<li><a href="{{ path('messageRecu_index', {'id': message.id }) }}"> Message reçu :</a></li>#}
{#<li><a href="{{ path('messageLu_index', {'id': message.id }) }}"> Message lu :</a></li>#}
{#<li><a href="{{ path('listeMessagesEnvoyer_index', {'id': message.id }) }}"> Liste des messages envoyer :</a></li>#}
{#<li><a href="{{ path('listeMessagesRecu_index', {'id': message.id }) }}"> Liste des messages reçu :</a></li>#}
</lu>
    
    <br />
    <a href="{{ path('nouveauMessage_index') }}">Nouveau message </a>
<br /><br />
    
    <table border="1">
            <thead>
                <tr>
                    <th> Id </th>
                    <th> Titre du message </th>
                    <th> Description </th>
                    <th> Creer date </th>
                    <th> Si le message est lu </th>
                    <th> Expediteur </th>
                    <th> Destinataire </th>
                    <th> Modifier </th>
<th> Afficher </th>
<th> Supprimer </t  h>
</tr>
            </thead>
            {% for message in message %}
<tbody>
<tr>
                                <td> {{ message.id }} </td>
<td> {{ message.titreMessage }} </td>
                <td> {{ message.description }} </td>
                <td> {{ message.creerDate|date("d/m/Y") }} </td>
<td> {{ message.siMessageLu }} </td>
                <td> {{ message.expediteur.nom }} </td>
                <td> {{ message.destinataire.nom }} </td>
                                <td><a href="{{ path('modifierMessage_index', {'id': message.id }) }}">Modifier</a></td>
<td><a href="{{ path('afficherMessage_index', {'id': message.id }) }}">afficher</a></td>
<td><a href="{{ path('supprimerMessage_index', {'id': message.id }) }}">Supprimer</a></td>
                </tr>
                {% else %}
                <tr>
                <td colspan="5">
                    Vous n'avez pas de messages enregistré dans votre base de données !
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

</div>
{% endblock %}

<br/><br/>

{% block footer %}
<p>
<a href="{{ path('accueil_index') }}"> Retour à la page d'accueil :</a><br>

</p>
{% endblock %}
{% endblock %}

templates/message/messagesEnvoyer.html.twig
{% extends 'base.html.twig' %}


{% block title %}
 Enregistrement d'un nouveau message 
 {% endblock %}

{% block content %}
 <br> <br>
 
    <h1> Enregistrement d'un nouveau message</h1>

    {{ include('messages/formulaireMessage.html.twig') }}<br>

    <a href="{{ path('message_index') }}">Liste des messages :</a><br>


{% endblock %}

templates/message/messagesLu.html.twig
{% extends 'base.html.twig' %}


{% block title %}
 Enregistrement d'un nouveau message 
 {% endblock %}

{% block content %}
 <br> <br>
 
    <h1> Enregistrement d'un nouveau message</h1>

    {{ include('messages/formulaireMessage.html.twig') }}<br>

    <a href="{{ path('message_index') }}">Liste des messages :</a><br>


{% endblock %}

templates/message/messagesReçu.html.twig
{% extends 'base.html.twig' %}


{% block title %}
 Enregistrement d'un nouveau message 
 {% endblock %}

{% block content %}
 <br> <br>
 
    <h1> Enregistrement d'un nouveau message</h1>

    {{ include('messages/formulaireMessage.html.twig') }}<br>

    <a href="{{ path('message_index') }}">Liste des messages :</a><br>


{% endblock %}

templates/message/modifierMessage.html.twig
{% extends 'base.html.twig' %}


{% block title %}
Modification  du message 
 {% endblock %}

{% block content %}
 <br> <br>
 
    <h1>
Modification  du message 
    </h1>

    {{ include('messages/formulaireMessage.html.twig') }}<br>

    <a href="{{ path('message_index') }}"> Retour à la liste des messages :</a><br>


{% endblock %}

templates/message/nouveauMessage.html.twig
{% extends 'base.html.twig' %}


{% block title %}
 Enregistrement d'un nouveau message 
 {% endblock %}

{% block content %}
 <br> <br>
 
    <h1> Enregistrement d'un nouveau message</h1>

    {{ include('messages/formulaireMessage.html.twig') }}<br>

    <a href="{{ path('message_index') }}">Liste des messages :</a><br>


{% endblock %}